Dev
CiscoDevNet/socialminer-sample-code pull request #13
Opened 2018-09-14 06:10 UTC by amj4kor

- Initial draft
- Read me

2018-09-16 16:05 UTC, umnagendra requested changes
@amj4kor - Bunch of comments, please take a look.
We can discuss in person.

2018-09-16 16:05 UTC, umnagendra commented on bubble-chat-scheduling/README.MD
> +# Cisco SocialMiner - Scheduling BubbleChat Sample
I have a big list of comments on the README contents and structure.
@amj4kor - Let's discuss in-person, too many to write here.

We need to make it better, and follow a similar structure as the other samples in this repo. See [here](https://github.com/CiscoDevNet/socialminer-sample-code/blob/master/customer-chat-proactive/README.md) and [here](https://github.com/CiscoDevNet/socialminer-sample-code/blob/master/chat-facebook-messenger/README.md) as references.

2018-09-16 16:05 UTC, umnagendra commented on bubble-chat-scheduling/bubble.html
> +<script type="application/javascript">
I think it is important here to add clear, verbose comments explaining that:

- Bubble chat deployment includes embedding a code snippet
- This code snippet is generated as result of configuring a "bubble" chat widget in appadmin
- This code will add an `iframe` into the webpage inside which bubble chat will be launched
- Refer lines starting from line 50 for actual scheduling example code

Otherwise, someone who comes here needs to go through all of the code till line 50 and be confused as to how this is related to scheduling. Adding a comment clearly sets the expectation so 3rd-party developers can point their focus to where they want to.

2018-09-16 16:05 UTC, umnagendra commented on bubble-chat-scheduling/bubble.html
> +        var smHost = 'sm1162.ajay.com';
This is an example - useful thing will be to keep generic hostnames (say, `socialminer.my-company.com`) so people can understand better.

Also, it wouldn't hurt to add a small comment next/above this.

```javascript
// Fully qualified, public hostname of SocialMiner
var smHost = 'socialminer.my-company.com';

// ID of the bubble chat widget
var widgetId = '3';
```

2018-09-16 16:05 UTC, umnagendra commented on bubble-chat-scheduling/bubble.html
> +<script src='./scripts/schedule.js'> </script>
I think it is important here too, to add clear, verbose comments explaining:

- that the below chunk of code illustrates how scheduling can be applied to show/hide bubble chat
- that actual schedule logic is implemented in `schedule.js` which needs to be hosted at an appropriate place by the 3rd-party developers
- that this `schedule.js` reads the actual schedule configuration from an external JSON file (refer them to the specific section in README for details on how to configure schedule)

DevNet samples aim to educate 3rd-party devs and naturally contain a lot of comments.

2018-09-16 16:05 UTC, umnagendra commented on bubble-chat-scheduling/bubble.html
> +<button onclick="displayBubblechatExample()">example1</button>
Why does the button say `example1`? Can we have something proper shown for this button value please?
Also, add verbose comment explaining why this button is there and what it does.

2018-09-16 16:05 UTC, umnagendra commented on bubble-chat-scheduling/bubble.html
> +function displayBubblechatExample() {
Function name `checkScheduleAndShowChatBubble()` is more appropriate. (The word `example` really does not mean anything here)

2018-09-16 16:05 UTC, umnagendra commented on bubble-chat-scheduling/bubble.html
> +        ciscoBubbleChat.showChatWindow();
Add verbose comments

2018-09-16 16:05 UTC, umnagendra commented on bubble-chat-scheduling/bubble.html
> +        alert('working hours closed');
IMPORTANT - verbose comment needed here indicating that 3rd-party developers can implement any actions during offline hours, and that the `alert()` is shown for illustrative purposes only, and that actual working hours, holiday info etc. can be read using the same `data.json` file and displayed.

2018-09-16 16:05 UTC, umnagendra commented on bubble-chat-scheduling/bubble.html
> +<body onload="readConfig('http://localhost:3000/scripts/data.json')">
`data.json`? How about `schedule_config.json` for clarity?

2018-09-16 16:05 UTC, umnagendra commented on bubble-chat-scheduling/bubble.html
> +<!-- Use the function 'ciscoBubbleChat.showChatWindow() as the event handler for initiating chat -->
You can remove this, since you have implemented the `showChatWindow()` invocation above.

2018-09-16 16:05 UTC, umnagendra commented on bubble-chat-scheduling/scripts/data.json
> +{
We'll need a section in README explaining how one should interpret this JSON file so they can edit it.

2018-09-16 16:05 UTC, umnagendra commented on bubble-chat-scheduling/scripts/schedule.js
> +var libraries = [
Please add detailed copyright, comments and everything that goes on top of every file in our DevNet sample.
Refer https://github.com/CiscoDevNet/socialminer-sample-code/blob/master/chat-facebook-messenger/src/app.js

2018-09-16 16:05 UTC, umnagendra commented on bubble-chat-scheduling/bubble.html
> +<!-- Add this script tag without any modification to the target webpage -->
Please add detailed copyright, comments and everything that goes on top of every file in our DevNet sample.
Refer https://github.com/CiscoDevNet/socialminer-sample-code/blob/master/chat-facebook-messenger/src/app.js

2018-09-16 16:05 UTC, umnagendra commented on bubble-chat-scheduling/scripts/schedule.js
> +  'https://cdnjs.cloudflare.com/ajax/libs/moment-timezone/0.5.13/moment-timezone.min.js',
Also add a comment explaining why we need all these JS files.

2018-09-16 16:05 UTC, umnagendra commented on bubble-chat-scheduling/scripts/schedule.js
> +function initialize() {
It will be a good idea to add clear comments (in jsDoc format) for each function so it is readable.

2018-09-16 16:05 UTC, umnagendra commented on bubble-chat-scheduling/scripts/schedule.js
> +//Below variables hold the Chat Schedule Configuration details as provided in the AppAdmin Schedule Configuration Page
What is `AppAdmin`? It is only a nickname for "Unified CCX Administration"

2018-09-16 16:05 UTC, umnagendra commented on bubble-chat-scheduling/scripts/schedule.js
> +    // document.getElementById("chatForm").style.display = "inline";
Clean-up code if you don't need it rather than commenting it out.

2018-09-16 16:05 UTC, umnagendra commented on bubble-chat-scheduling/scripts/schedule.js
> +    // alert("Bubble chat displayed");
Clean-up code if you don't need it rather than commenting it out.

2018-09-16 16:05 UTC, umnagendra commented on bubble-chat-scheduling/scripts/schedule.js
> +    // alert('bubble chat displayed');
Clean-up code if you don't need it rather than commenting it out.

2018-09-16 16:05 UTC, umnagendra commented on bubble-chat-scheduling/scripts/schedule.js
> +    // document.getElementById("closedMessage").style.display = "inline";
Clean-up code if you don't need it rather than commenting it out.

2018-09-16 16:05 UTC, umnagendra commented on bubble-chat-scheduling/scripts/schedule.js
> +function displayBubblechatExample1() {
Why is this function here? Shouldn't it be removed, now that it has been moved out to the HTML file?

2018-09-17 05:02 UTC, amj4kor commented on bubble-chat-scheduling/scripts/schedule.js
> +var libraries = [
added comments

2018-09-19 06:50 UTC, umnagendra approved these changes

2018-09-19 06:50 UTC, merged